### ISSUE TITLE
Can i use dogecoin_client to access different daemons?

### ISSUE THREAD

**Issue by EMRJ** [repp/dogecoin_client#2]
I have installed dogecoin_client gem, and accessed litecoin daemon(json rpc), is it possible to access any daemon using this gem

**Comment by repp** [comment]
I can't say for sure because I've only tested it with Dogecoin but because a lot of altcoins (doge included) are just forks of litecoin the json rpc apis are very similar if not identical. I haven't looked into it so there might be a few inconsistencies but in general you shouldn't have too much trouble using the dogecoin client gem with coins' daemons.
